#!/bin/bash

while [ "$1" != "" ]; do
	FILE=$1
	m4 -I $(dirname "$FILE") "$FILE" > build/ex.bif
	grep -e "^[^#]" build/ex.bif > build/exb.bif
	OUTFILE=`echo $FILE | sed -e 's/\.bif/\.b/g'`
	./biffle build/exb.bif > $OUTFILE
	shift
done;
