#!/bin/bash
default="\e[39m"
bfi=bfc

while [ "$1" != "" ]; do
	color="\e[91m"
	FILE=$1
	echo "$FILE: "
	expected=$(head -n 1 `echo $FILE | sed -e 's/\.b/\.bif/'`)
	expected=$(echo -e "$expected" | sed -e 's/^;//')
    exe=$(echo `basename $FILE` | sed -e 's/\..*//')
	output=$($bfi $FILE; ./$exe)
	if [ "$expected" = "$output" ]; then
		color="\e[92m"
	else
		echo "expected $expected"
	fi
	echo -e "$color$output$default"
	shift
done;
